services:
  bot:
    build: .
    image: my_bot
    container_name: bot_debug
    restart: always
    environment:
      - DOCKER_BUILDKIT=0
      - BOT_TOKEN=${BOT_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"