services:
  bot:
    build: .
    image: my_bot
    container_name: bot_debug
    restart: always
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_TOKEN=${BOT_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
